version: 2
authtoken: 1gyXwUIw6lggncDzugyUnlp0aCu_nsNwXycmPyH7eXFvrUyL
tunnels:
  first-tunnel:
    addr: 3000 # Local port number for your first service
    proto: http
  second-tunnel:
    addr: 3001 # Local port number for your second service
    proto: http
  
       